// ---------------- global using ---------------- //
global using HandyControl.Controls;
global using Microsoft.Win32;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Security.AccessControl;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using System.Windows.Media.Animation;
global using System.Windows.Media.Imaging;
global using UI;
global using XFP.ICora.Controls;
global using XFP.ICora.Controls.Basic;
global using XFP.ICora.Hoyolab;
global using XFP.ICora.Hoyolab.Account;
global using XFP.ICora.Hoyolab.Core;
global using XFP.ICora.Model;
global using XFP.ICora.Utils;
global using XFP.ICora.Utils.Base;
global using XFP.ICora.Utils.Log;
global using XFP.ICora.Utils.Model;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using XFP.ICora.Controls.Game.Utils;
global using XFP.ICora.Utils.Model.Files;
global using System.Security.Principal;
// ---------------- global using as ---------------- //
global using MessageBox = System.Windows.MessageBox;
global using Window = System.Windows.Window;
